# -*- coding: utf-8 -*-
"""practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KjxADYq9hC9mhB7pNjqFfgrV0S_fhPpX

Function to reverse an array in python
"""

def revarr(a):
  # //function to reverse an array
  count=0
  reverse=[]
  n=len(a)-1
  for i in range(n+1):
    if count is 0:
     reverse.append(a[n])
     count+=1
    else:
      reverse.append(a[n-i])
  return reverse

print(revarr([6,2,3,4,5,8]))

def insertion(a):
  #program to perform insertion sort
  
  #Arraysorted=[]
  for i in range(len(a)):
    key=a[i]
    j=i-1
    while j>=0 and a[j]>key :
      a[j+1]=a[j]
      j=j-1
      a[i-1]=key
      print(a)

insertion([9,3,5,1,6,4])

def countnumbers(a):
  # algorithm to count repeated letters in a word

  a=a.casefold()
  count={}
  for i in a:
    if i in count:
      count[i]+=1
    else:
      count[i]=1
  for key in count:
   if count[key] > 0:
    print(key,count[key])

    
  
countnumbers('Decapitationed')

def countnumbers(a):

    """ 
    Function to count the pairs given an array
    @parms number of array
    @returns count of numbers that cant be paired 
      """

    count={}
    pairedkey_count=list()
    for i in a:
      if i in count:
        count[i]+=1
      else:
        count[i]=1
    for key in count:
     if (count[key] % 2):
        pairedkey_count.append(key)

    return len(pairedkey_count)

input_array=[1,2,3,4,4,5,6,7,3,4,5,4,5]
text='for "{}" array the count of elements that cannot be paired are {}.'
print(text.format(input_array,countnumbers(input_array)))

graph={}

def add_edge(u,v):
  graph[u]=v

def SearchDoors(source):
  visited=[False for i in graph]

  queue=[]
  queue.append(source)

  visited[source]=True

  while queue:
    s=queue.pop(0)
    print(s,end=' ')

    for i in graph:
      if visited[i]==False:
        queue.append(i)
        visited[i]=True

doors = [[0,1], [1,2], [1,3], [2,4], [4,5], [3,4]]
for i in doors:
  add_edge(i[0],i[1])

SearchDoors(0)