# -*- coding: utf-8 -*-
"""practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KjxADYq9hC9mhB7pNjqFfgrV0S_fhPpX

Function to reverse an array in python
"""

def revarr(a):
  # //function to reverse an array

  count=0
  reverse=[]
  n=len(a)-1
  for i in range(n+1):
    if count is 0:
     reverse.append(a[n])
     count+=1
    else:
      reverse.append(a[n-i])
  return reverse

print(revarr([6,2,3,4,5,8]))

def insertion(a):
  #program to perform insertion sort
  
  i=2
  for i in range(len(a)):
    key=a[i]
    j=i-1
    while j>=0 and a[j]>key :
      a[j+1]=a[j]
      j=j-1
      a[i-1]=key
      return a

print (insertion([9,3,5,1,6,4]))

def countnumbers(a):
  # algorithm to count repeated letters in a word

  a=a.casefold()
  count={}
  for i in a:
    if i in count:
      count[i]+=1
    else:
      count[i]=1
  for key in count:
   if count[key] > 0:
    print(key,count[key])

    
  
countnumbers('Decapitationed')